#!/bin/bash

echo "=========================================="
echo "Azure Publish Profile for GitHub Secret"
echo "=========================================="
echo ""
echo "Kopiere diesen gesamten Inhalt (inklusive der XML-Tags)"
echo "und füge ihn als GitHub Secret ein:"
echo ""
echo "Name: AZURE_WEBAPP_PUBLISH_PROFILE"
echo ""
echo "=========================================="
echo ""
cat /tmp/azure-publish-profile.xml
echo ""
echo "=========================================="
echo ""
echo "Schritte:"
echo "1. Gehe zu deinem GitHub Repository"
echo "2. Settings → Secrets and variables → Actions"
echo "3. New repository secret"
echo "4. Name: AZURE_WEBAPP_PUBLISH_PROFILE"
echo "5. Value: <obigen XML-Inhalt einfügen>"
echo "6. Add secret"
echo ""
